# Generated by Django 4.2.15 on 2024-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproj1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
