# Generated by Django 4.2.15 on 2024-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproj1', '0004_alter_persondetails_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetails',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
