# Generated by Django 4.2.15 on 2024-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dproj1', '0006_alter_persondetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetails',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
